<template>
  <div class="q-mb-sm">
    <q-input
      v-model="search"
      label="Search for skills"
      outlined
      clearable
    ></q-input>
    <q-toggle v-model="preciseSearching" label="Precise searching"></q-toggle>
  </div>

  <q-virtual-scroll
    :items="filteredSkills"
    v-slot="{ item }"
    style="height: calc(100vh - 160px)"
  >
    <div class="q-mb-lg">
      <div class="text-h5">{{ item.category }}</div>
      <div class="row" :class="{ 'justify-center': $q.screen.lt.md }">
        <transition-group
          appear
          enter-active-class="animated zoomIn slow"
          leave-active-class="animated zoomOut"
        >
          <div
            v-for="(skill, key) in item.items"
            :key="key"
            class="q-my-md q-mx-sm"
            :class="{
              'col-6': $q.screen.lt.sm,
              'col-4': $q.screen.lt.md,
              'col-3': $q.screen.gt.md,
            }"
            style="width: auto"
          >
            <q-card flat bordered class="q-pa-sm skills-card">
              <div class="row justify-center items-center">
                <q-knob
                  v-model="skill.rating"
                  show-value
                  size="110px"
                  :thickness="0.2"
                  :max="10"
                  :color="$q.dark.isActive ? 'blue' : 'black'"
                  track-color="blue-grey-2"
                  class="q-ma-md"
                  readonly
                />
              </div>
              <q-separator class="q-mb-md"></q-separator>
              <div class="text-center">{{ skill.label }}</div>
              <div class="text-center">Last Used: {{ skill.lastUsed }}</div>
              <div class="text-center">Usage: {{ skill.yearsExp }} year(s)</div>
            </q-card>
          </div>
        </transition-group>
      </div>
    </div>
  </q-virtual-scroll>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue';

const search = ref('');
const preciseSearching = ref(false);

const skills = ref([
  {
    category: 'Languages & Frameworks',
    items: [
      {
        label: 'PHP',
        rating: 8,
        lastUsed: 'Present',
        yearsExp: 12,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'web',
          'rest',
          'api',
          'rest api',
          'rest-api',
          'restful',
          'server side',
          'back-end',
          'backend',
          'back end',
          'full-stack',
          'full stack',
          'synchronus',
          'single threaded',
        ],
      },
      {
        label: 'Laravel',
        rating: 8,
        lastUsed: 'Present',
        yearsExp: 7,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'api',
          'rest api',
          'rest-api',
          'restful',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'full-stack',
          'full stack',
          'synchronus',
          'single threaded',
        ],
      },
      {
        label: 'Javascript',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 12,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'api',
          'rest api',
          'rest-api',
          'restful',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'mobile',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'synchronus',
          'single threaded',
          'real-time',
          'real time',
        ],
      },
      {
        label: 'Typescript',
        rating: 6.5,
        lastUsed: 'Present',
        yearsExp: 3,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'mobile',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'synchronus',
          'single threaded',
          'real-time',
          'real time',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Node JS',
        rating: 6.5,
        lastUsed: 'Present',
        yearsExp: 4,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'mobile',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'synchronus',
          'single threaded',
          'real-time',
          'real time',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Nest JS',
        rating: 6.5,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'typeorm',
          'prisma',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'synchronus',
          'single threaded',
          'real-time',
          'real time',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Express JS',
        rating: 6.5,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'mobile',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'synchronus',
          'single threaded',
          'real-time',
          'real time',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Vue JS',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 5,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'mobile',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'pinia',
          'vuex',
          'vue router',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'synchronus',
          'single threaded',
          'real-time',
          'real time',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Nuxt JS',
        rating: 6,
        lastUsed: '2020',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'mobile',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'full-stack',
          'full stack',
          'asynchronus',
          'multi-threading',
          'real-time',
          'real time',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
    ],
  },
  {
    category: 'Databases & Caching',
    items: [
      {
        label: 'MySQL',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 12,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'mysql',
          'sql',
          'relational',
          'database',
          'db',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'MSSQL',
        rating: 5,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'mssql',
          'sql',
          'relational',
          'database',
          'db',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'SQLite',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'sqlite',
          'sql',
          'relational',
          'database',
          'db',
          'local',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Redis',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 3,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'nosql',
          'non-relational',
          'database',
          'db',
          'caching',
          'cache',
          'redis',
          'full-stack',
          'full stack',
        ],
      },
    ],
  },
  {
    category: 'Object Relational Mapping',
    items: [
      {
        label: 'Eloquent',
        rating: 6,
        lastUsed: '2020',
        yearsExp: 4,
        tags: [
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'laravel',
          'api',
          'rest api',
          'rest-api',
          'restful',
          'nosql',
          'relational',
          'non-relational',
          'database',
          'db',
          'sql',
          'mysql',
          'mssql',
          'sqlite',
          'orm',
          'full-stack',
          'full stack',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Typeorm',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'server side',
          'back-end',
          'backend',
          'back end',
          'nosql',
          'relational',
          'non-relational',
          'database',
          'db',
          'sql',
          'mysql',
          'mssql',
          'sqlite',
          'orm',
          'typeorm',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Prisma',
        rating: 6,
        lastUsed: '2023',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'server side',
          'back-end',
          'backend',
          'back end',
          'nosql',
          'relational',
          'non-relational',
          'database',
          'db',
          'sql',
          'mysql',
          'mssql',
          'sqlite',
          'orm',
          'prisma',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Sequelize',
        rating: 5,
        lastUsed: '2019',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'server side',
          'back-end',
          'backend',
          'back end',
          'nosql',
          'relational',
          'non-relational',
          'database',
          'db',
          'sql',
          'mysql',
          'mssql',
          'sqlite',
          'orm',
          'sequelize',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Doctrine',
        rating: 4,
        lastUsed: '2020',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'server side',
          'back-end',
          'backend',
          'back end',
          'nosql',
          'relational',
          'non-relational',
          'database',
          'db',
          'sql',
          'mysql',
          'mssql',
          'sqlite',
          'orm',
          'doctrine',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
    ],
  },
  {
    category: 'API Securities',
    items: [
      {
        label: 'JSON Web Token',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'security',
          'rest',
          'spa',
          'single page application',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Laravel Sanctum',
        rating: 5,
        lastUsed: '2020',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'security',
          'rest',
          'spa',
          'single page application',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Passport',
        rating: 2,
        lastUsed: '2017',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'security',
          'rest',
          'spa',
          'single page application',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
    ],
  },
  {
    category: 'Push Notifications & Real-time data',
    items: [
      {
        label: 'Pusher',
        rating: 3,
        lastUsed: '2023',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'security',
          'rest',
          'spa',
          'single page application',
          'real-time',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Web Socket',
        rating: 3,
        lastUsed: '2023',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'security',
          'rest',
          'spa',
          'single page application',
          'real-time',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Socket.io',
        rating: 3,
        lastUsed: '2023',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'nest js',
          'next js',
          'nuxt js',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'security',
          'rest',
          'spa',
          'single page application',
          'real-time',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
    ],
  },
  {
    category: 'UI Frameworks',
    items: [
      {
        label: 'Quasar Framework',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Bootstrap',
        rating: 7,
        lastUsed: '2021',
        yearsExp: 9,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Bootstrap Vue',
        rating: 7,
        lastUsed: '2020',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Vuetify',
        rating: 7,
        lastUsed: '2020',
        yearsExp: 2,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Tailwind',
        rating: 5,
        lastUsed: '2022',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'full-stack',
          'full stack',
        ],
      },
    ],
  },
  {
    category: 'Mobile Development Frameworks and Tools',
    items: [
      {
        label: 'Ionic (Vue)',
        rating: 4,
        lastUsed: '2022',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'react',
          'angular',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Capacitor',
        rating: 4,
        lastUsed: 'Present',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Flutter',
        rating: 2,
        lastUsed: '2021',
        yearsExp: 1,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
    ],
  },
  {
    category: 'IDE & Other Tools',
    items: [
      {
        label: 'Visual Studio Code',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 5,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'nest js',
          'next js',
          'nuxt js',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Sublime',
        rating: 6,
        lastUsed: '2017',
        yearsExp: 3,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'nest js',
          'next js',
          'nuxt js',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Notepad ++',
        rating: 6,
        lastUsed: '2015',
        yearsExp: 3,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'nest js',
          'next js',
          'nuxt js',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'full-stack',
          'full stack',
        ],
      },
      {
        label: 'Docker Desktop',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'nest js',
          'next js',
          'nuxt js',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'deployment',
          'dev-ops',
          'dev ops',
          'full-stack',
          'full stack',
          'api',
          'rest api',
          'rest-api',
          'restful',
        ],
      },
      {
        label: 'Github Desktop',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'jsx',
          'web',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'vue',
          'quasar',
          'ionic',
          'capacitor',
          'nest js',
          'next js',
          'nuxt js',
          'mobile',
          'api',
          'rest',
          'spa',
          'pwa',
          'single page application',
          'real-time',
          'responsive',
          'android',
          'ios',
          'linux application',
          'windows application',
          'deployment',
          'devops',
          'pipeline',
        ],
      },
      {
        label: 'MySQL Workbench',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 6,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'mysql',
          'sql',
          'relational',
          'database',
          'db',
        ],
      },
      {
        label: 'Heidi SQL',
        rating: 8,
        lastUsed: 'Present',
        yearsExp: 4,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'mysql',
          'mssql',
          'sql',
          'sqlite',
          'relational',
          'database',
          'db',
        ],
      },
      {
        label: 'DBeaver CE',
        rating: 8,
        lastUsed: 'Present',
        yearsExp: 4,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'mysql',
          'mssql',
          'sql',
          'sqlite',
          'relational',
          'database',
          'db',
        ],
      },
    ],
  },
  {
    category: 'Deployment Tools and CI/CD',
    items: [
      {
        label: 'Git',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 9,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
        ],
      },
      {
        label: 'Docker',
        rating: 4,
        lastUsed: 'Present',
        yearsExp: 5,
        tags: [
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Azure Pipelines',
        rating: 4,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Bitbucket Pipelines',
        rating: 4,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Azure DevOps',
        rating: 3,
        lastUsed: 'Present',
        yearsExp: 2,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Jenkins',
        rating: 3,
        lastUsed: '2019',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Github',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 4,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Azure Repositories',
        rating: 5,
        lastUsed: 'Present',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'Bitbucket',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 4,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
      {
        label: 'GitLab',
        rating: 4,
        lastUsed: '2020',
        yearsExp: 1,
        tags: [
          'php',
          'laravel',
          'symfony',
          'code igniter',
          'yii',
          'cake php',
          'wordpress',
          'magento',
          'javascript',
          'typescript',
          'node',
          'js',
          'ts',
          'php',
          'server side',
          'back-end',
          'backend',
          'back end',
          'front-end',
          'frontend',
          'front end',
          'full-stack',
          'full stack',
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
        ],
      },
    ],
  },
  {
    category: 'Operating Systems',
    items: [
      {
        label: 'Linux',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 9,
        tags: [
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
          'web server',
          'web-server',
          'ubuntu',
          'debian',
          'arch',
          'fedora',
          'centos',
          'alpine',
          'linux',
          'operating system',
          'system administration',
        ],
      },
      {
        label: 'Windows',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 12,
        tags: [
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
          'operating system',
          'system administration',
          'microsoft',
          'azure',
        ],
      },
      {
        label: 'Mac',
        rating: 5,
        lastUsed: '2023',
        yearsExp: 1,
        tags: [
          'deployment',
          'devops',
          'dev ops',
          'container',
          'virtual',
          'docker',
          'kubernetes',
          'operating system',
          'system administration',
          'apple',
          'mac',
          'mac os',
          'mac os x',
          'azure',
        ],
      },
    ],
  },
  {
    category: 'Non-Technical Skills & Project Management Tools',
    items: [
      {
        label: 'Agile Scrum',
        rating: 6,
        lastUsed: 'Present',
        yearsExp: 9,
        tags: [
          'team player',
          'agile',
          'scrum',
          'dsm',
          'sprint',
          'sprint planning',
          'project management',
          'business',
          'scrum master',
          'product owner',
          'estimation',
          'story points',
          'sprint goal',
          'sprint goals',
          'user story',
          'sdlc',
          'software development life cycle',
        ],
      },
      {
        label: 'Rapid Development',
        rating: 6,
        lastUsed: '2022',
        yearsExp: 3,
        tags: [
          'team player',
          'team',
          'rapid',
          'project management',
          'sdlc',
          'software development life cycle',
        ],
      },
      {
        label: 'Waterfall',
        rating: 3,
        lastUsed: 'n/a',
        yearsExp: 0,
        tags: [
          'team player',
          'team',
          'waterfall',
          'water-fall',
          'water fall',
          'project management',
          'sdlc',
          'software development life cycle',
        ],
      },
      {
        label: 'Jira',
        rating: 7,
        lastUsed: 'Present',
        yearsExp: 4,
        tags: [
          'team player',
          'agile',
          'scrum',
          'dsm',
          'sprint',
          'sprint planning',
          'project management',
          'business',
          'scrum master',
          'product owner',
          'estimation',
          'story points',
          'sprint goal',
          'sprint goals',
          'user story',
          'sdlc',
          'software development life cycle',
          'waterfall',
          'water-fall',
          'water fall',
          'rapid',
        ],
      },
      {
        label: 'Trello',
        rating: 7,
        lastUsed: '2020',
        yearsExp: 2,
        tags: [
          'team player',
          'agile',
          'scrum',
          'dsm',
          'sprint',
          'sprint planning',
          'project management',
          'business',
          'scrum master',
          'product owner',
          'estimation',
          'story points',
          'sprint goal',
          'sprint goals',
          'user story',
          'sdlc',
          'software development life cycle',
          'waterfall',
          'water-fall',
          'water fall',
          'rapid',
        ],
      },
      {
        label: 'Redmine',
        rating: 5,
        lastUsed: '2017',
        yearsExp: 2,
        tags: [
          'team player',
          'agile',
          'scrum',
          'dsm',
          'sprint',
          'sprint planning',
          'project management',
          'business',
          'scrum master',
          'product owner',
          'estimation',
          'story points',
          'sprint goal',
          'sprint goals',
          'user story',
          'sdlc',
          'software development life cycle',
          'waterfall',
          'water-fall',
          'water fall',
          'rapid',
        ],
      },
    ],
  },
]);

const filteredSkills = computed(() => {
  if (!search.value) return skills.value;
  const lowerSearch = search.value.toLowerCase();
  return skills.value
    .map((category) => {
      const items = category.items.filter((skill) =>
        preciseSearching.value
          ? skill.label.toLowerCase().includes(lowerSearch)
          : skill.tags.includes(lowerSearch)
      );
      if (items.length) {
        return { ...category, items };
      }
      return null;
    })
    .filter((category) => category !== null);
});
</script>

<style lang="scss" scoped>
.skills-card {
  transition: all 0.5s ease-in-out;
}
.q-card.skills-card:hover {
  border: 1px solid;
}
.q-card--dark.skills-card:hover {
  background: inherit;
}
</style>
